# Generated by Django 3.1.1 on 2020-09-24 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_auto_20200921_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subscription',
            field=models.ManyToManyField(blank=True, related_name='subs', to=settings.AUTH_USER_MODEL),
        ),
    ]
