# Generated by Django 3.1.1 on 2020-09-26 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_board_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='author',
        ),
    ]
