# Generated by Django 3.1.1 on 2020-09-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replies',
        ),
    ]
