# Generated by Django 3.1.1 on 2020-09-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(max_length=1000, null=True, verbose_name='Profile Description'),
        ),
    ]
