# Generated by Django 3.1.1 on 2020-09-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200920_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Default User Profile. To personalize and add info about yourself, scroll down and update!', max_length=1000, verbose_name='Profile Description'),
        ),
    ]
